<?php
/**
 * OnlineBiz Software Solution
 * 
 * @project lendclick.com.au
 * @version 0.0.1
 * @encoding UTF-8
 * @author Joe Vu<joe@onlinebizsoft.com>
 * @see http://onlinebizsoft.com
 * @copyright (c) 2017 , OnlineBiz Software Solution
 * 
 * Create at: Jan 5, 2018 7:32:51 PM
 */
?>
<div class="wapper_app">
    <div id="app-frm">
        <div class="um-field um-field-text um-field-type_text">
            <div class="um-field-label">
                <label for="loan_customer_name">Full Name:</label>
                <div class="um-clear"></div>                  
            </div>
            <div class="um-field-area">
                <input class="um-form-field" type="text" onkeyup="fieldOnChange(this)" onchange="fieldOnChange(this)" name="loan_customer_name" id="loan_customer_name" placeholder="Full name" value="<?php echo $loan_customer_name ?>" required=""/>
                <i class="fa fa-check fa-input" aria-hidden="true" <?php if(isset($loan_customer_name) && strlen($loan_customer_name) > 0):?>style="display: block !important"<?php endif?>></i>
            </div>
        </div>
        <div class="um-field um-field-text um-field-type_text"/>
        <div class="um-field-label">
            <label for="loan_dob">Birthday:</label>
            <div class="um-clear"></div>                  
        </div>
        <div class="um-field-area">
            <input class="um-form-field" type="text" onkeyup="fieldOnChange(this)" onchange="fieldOnChange(this)" name="loan_dob" id="loan_dob" value="<?php echo isset($loan_dob) ? $loan_dob : '' ?>" required=""/>
            <i class="fa fa-check fa-input" aria-hidden="true" <?php if(isset($loan_dob) && strlen($loan_dob) > 0):?>style="display: block !important"<?php endif?>></i>
        </div> 
    </div>
    <div class="um-field um-field-text um-field-type_text">
        <div class="um-field-label">
            <label for="loan_customer_email">Email address:</label>
            <div class="um-clear"></div>                  
        </div>
        <div class="um-field-area">
            <input class="um-form-field " type="text" onkeyup="fieldOnChange(this)" onchange="fieldOnChange(this)" name="loan_customer_email" value="<?php echo $loan_customer_email ?>" id="loan_customer_email" placeholder="Email address" required=""/>
            <i class="fa fa-check fa-input" aria-hidden="true" <?php if(isset($loan_customer_email) && strlen($loan_customer_email) > 0):?>style="display: block !important"<?php endif?>></i>
        </div>
    </div>
    <div class="um-field um-field-text um-field-type_text">
        <div class="um-field-label">
            <label for="first_name">Phone:</label>
            <div class="um-clear"></div>                  
        </div>
        <div class="um-field-area">
            <input class="um-form-field" type="text" onkeyup="fieldOnChange(this)" onchange="fieldOnChange(this)" name="loan_customer_phone" id="loan_customer_phone"  value="<?php echo isset($loan_customer_phone) ? $loan_customer_phone : '' ?>" required=""/>
            <i class="fa fa-check fa-input" aria-hidden="true" <?php if(isset($loan_customer_phone) && strlen($loan_customer_phone) > 0):?>style="display: block !important"<?php endif?>></i>
        </div>
    </div>
    <?php
    $abn_info = array();
    if (isset($loan_abn)) {
        $abn_info = $this->getAbnInfo($loan_abn);
    }
    ?>
    <div class="um-field  um-field-text um-field-type_text" >
        <div class="um-field-label">
            <label for="first_name">ABN:</label>
            <div class="um-clear"></div>                  
        </div>
        <div class="um-field-area abn-wapepr">
            <input  class="um-form-field " type="text" onkeyup="abnChange(this)" onchange="abnChange(this)" name="loan_abn" id="loan_abn" placeholder="ABN" value="<?php echo isset($loan_abn) ? $loan_abn : '' ?>"/>
            <i class="fa fa-check fa-input" aria-hidden="true"></i>
            <span class="loadding">Please wait...</span>
            <span class="abn-search-link"><?php _e('Not sure? Try search for your ABN') ?> <a style="text-decoration:underline" href="http://abr.business.gov.au" target="_blank">here</a></span>
            <span class="error"><?php _e('Enter a valid ABN number') ?></span>
            <ul class="app-abn-info" style="display: <?php if ($abn_info): ?>block<?php else: ?>none<?php endif ?>">
                <li><span class="label-abn"><i class="fa fa-check" style="display: inline !important; position: initial!important" aria-hidden="true"></i> <?php _e('Business Legal Name') ?></span>: <span class="abn-val-name"><?php echo isset($abn_info['bussiness']) ? $abn_info['bussiness']['name'] : '' ?></span></li>
                <li><span class="label-abn"><i class="fa fa-check" style="display: inline !important;  position: initial!important" aria-hidden="true"></i> <?php _e('Registration Date') ?></span>: <span class="abn-val-date"><?php echo isset($abn_info['bussiness']) ? $abn_info['bussiness']['effectiveFrom'] : '' ?></span></li>
                <li><span class="label-abn"><i class="fa fa-check" style="display: inline !important;  position: initial!important" aria-hidden="true"></i> <?php _e('State') ?></span>: <span class="abn-val-state"><?php echo isset($abn_info['bussiness']) ? $abn_info['bussiness']['stateName'] : '' ?></span></li>
            </ul>            
        </div>
    </div>
    <div class="um-field  um-field-text um-field-type_text" >
        <div class="um-field-label">
            <label for="first_name">Business Name:</label>
            <div class="um-clear"></div>                  
        </div>
        <div class="um-field-area">
            <input  class="um-form-field " type="text" onkeyup="fieldOnChange(this)" onchange="fieldOnChange(this)" name="loan_customer_business" id="loan_customer_business" placeholder="Business Name" value="<?php echo isset($loan_customer_business) ? $loan_customer_business : '' ?>"/>
            <i class="fa fa-check fa-input" aria-hidden="true" <?php if(isset($loan_customer_business) && strlen($loan_customer_business) > 0):?>style="display: block !important"<?php endif?>></i>
        </div>
    </div>
    <div class="um-field  um-field-text um-field-type_text" >
        <div class="um-field-label">
            <label for="first_name">Industry:</label>
            <div class="um-clear"></div>                  
        </div>
        <div class="um-field-area">
            <?php
            echo $this->getIndustrySelect('loan_industry', 'loan_industry', isset($loan_industry) ? $loan_industry : '', array(
                'class' => 'um-form-field',
                'required' => ''
            ));
            ?>
        </div>
    </div>
    <div class="um-field  um-field-text um-field-type_text" >
        <div class="um-field-label">
            <label for="first_name">Driving License Number:</label>
            <div class="um-clear"></div>                  
        </div>
        <div class="um-field-area">
            <input  class="um-form-field " type="text" name="loan_driving_license_number" id="loan_driving_license_number" placeholder="Driving License Number" value="<?php echo isset($loan_driving_license_number) ? $loan_driving_license_number : '' ?>"/>
        </div>
    </div>
    <div class="um-field  um-field-text um-field-type_text" >
        <div class="um-field-label">
            <label for="first_name">Loan Amount(USD):</label>
            <div class="um-clear"></div>                  
        </div>
        <div class="um-field-area">
            <div class="loan-slider-wapper">
                <div id="loan-slider"></div>
                <span class="loan-min limit">$5,000</span>
                <span class="loan-max limit">$1,000,000</span>
            </div>
            <input  class="um-form-field " type="text" name="loan_amount" value="<?php echo isset($loan_amount) ? (is_numeric($loan_amount) ? sprintf('$%s', number_format($loan_amount)) : $loan_amount) : '' ?>" id="loan_amount" placeholder="Loan Amount" required=""/>
        </div>
    </div>
    <div class="um-field  um-field-text um-field-type_text" >
        <div class="um-field-label">
            <label for="first_name">Loan Term (Months):</label>
            <div class="um-clear"></div>                  
        </div>
        <div class="um-field-area">
            <?php
            $loan_terms = isset($loan_terms) ? $loan_terms : '';
            $termCollection = array('Any', '3-6', '6-12', '12-24', '24+');
            ?>
            <select id="loan_terms" name="loan_terms">
                <?php foreach ($termCollection as $termName): ?>
                    <?php if ($termName == $loan_terms): ?>
                        <option value="<?php echo $termName ?>" selected=""><?php echo $termName ?></option>
                    <?php else: ?>
                        <option value="<?php echo $termName ?>"><?php echo $termName ?></option>
                    <?php endif ?>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div class="um-field  um-field-text um-field-type_text" >
        <div class="um-field-label">
            <label for="first_name">Loan Products:</label>
            <div class="um-clear"></div>                  
        </div>
        <div class="um-field-area">
            <?php
            $selected = is_array($loan_products) ? $loan_products : explode(',', $loan_products);
            $collection = array('Unsecured Business Loans', 'Invoice Finance', 'Line of Credit / Trade Finance', 'Equipment Finance', 'Vehicle Finance', 'Property Development Finance');
            ?>
            <select name="loan_products[]" multiple="" class="form-control full-width" required="">
                <?php
                foreach ($collection as $k => $productName):
                    ?>
                    <?php if (in_array($k, $selected)): ?>
                        <option value="<?php echo $k ?>" selected=""><?php echo $productName ?></option>
                    <?php else: ?>
                        <option value="<?php echo $k ?>"><?php echo $productName ?></option>
                    <?php endif; ?>
                    <?php
                endforeach;
                ?>
            </select>
        </div>
    </div>
    <div class="um-field  um-field-text um-field-type_text" >
        <div class="um-field-label">
            <label for="first_name">Time of business operating?</label>
            <div class="um-clear"></div>                  
        </div>
        <div class="um-field-area">
            <?php
            $selected = isset($time_of_business_operating) ? $time_of_business_operating : '';
            $collection = array('Less than 3 months', '3-5 months', '6-12 months', '1-2 years', '3-5 years', 'More than 5 years');
            ?>
            <select id="time_of_business_operating" name="time_of_business_operating" class="form-control full-width">
                <?php
                foreach ($collection as $k => $timeName):
                    ?>
                    <?php if ($selected == $timeName): ?>
                        <option value="<?php echo $timeName ?>" selected=""><?php echo $timeName ?></option>
                    <?php else: ?>
                        <option value="<?php echo $timeName ?>"><?php echo $timeName ?></option>
                    <?php endif; ?>
                    <?php
                endforeach;
                ?>
            </select>
        </div>
    </div>
    <div class="um-field  um-field-text um-field-type_text" >
        <div class="um-field-label">
            <label for="first_name">Monthly revenue? (average over past 6 months)</label>
            <div class="um-clear"></div>                  
        </div>
        <div class="um-field-area">
            <?php
            $selected = isset($loan_average_revenue) ? $loan_average_revenue : '';
            $collection = array('$0 - $10k', '$10k - $25k', '$100k - $250k', '$250k - $500k', '$500k+');
            ?>
            <select id="loan_average_revenue" name="loan_average_revenue" class="form-control full-width">
                <?php
                foreach ($collection as $k => $revenueName):
                    ?>
                    <?php if ($selected == $revenueName): ?>
                        <option value="<?php echo $revenueName ?>" selected=""><?php echo $revenueName ?></option>
                    <?php else: ?>
                        <option value="<?php echo $revenueName ?>"><?php echo $revenueName ?></option>
                    <?php endif; ?>
                    <?php
                endforeach;
                ?>
            </select>
        </div>
    </div>
    <div class="um-field  um-field-text um-field-type_text" >
        <div class="um-field-label">
            <label for="first_name">Additional contact number:</label>
            <div class="um-clear"></div>                  
        </div>
        <div class="um-field-area">
            <input  class="um-form-field " type="text" onkeyup="fieldOnChange(this)" onchange="fieldOnChange(this)"  value="<?php echo isset($business_phone_number) ? $business_phone_number : '' ?>" name="business_phone_number" id="business_phone_number" placeholder="Additional contact number" >
            <i class="fa fa-check fa-input" aria-hidden="true" <?php if(isset($business_phone_number) && strlen($business_phone_number) > 0):?>style="display: block !important"<?php endif?>></i>
        </div>
    </div>
    <div class="um-field  um-field-text um-field-type_text" >
        <div class="um-field-label">
            <label for="first_name">Best time to call:</label>
            <div class="um-clear"></div>                  
        </div>
        <div class="um-field-area">
            <input  class="um-form-field " type="text" onkeyup="fieldOnChange(this)" onchange="fieldOnChange(this)" value="<?php echo isset($best_time_to_reach) ? $best_time_to_reach : '' ?>" name="best_time_to_reach" id="best_time_to_reach" placeholder="Best time to call" >
            <i class="fa fa-check fa-input" aria-hidden="true" <?php if(isset($best_time_to_reach) && strlen($best_time_to_reach) > 0):?>style="display: block !important"<?php endif?>></i>
        </div>
    </div> 
    <div class="um-col-alt um-col-alt-b">
        <div class="um-left"><a href="javascript:void()" id="um_app_submit" class="um-button btn btn-default">Update Application</a> </div><div class="loaderx"></div>
        <div class="um-clear"></div>
    </div>
    <input type="hidden" name="app_id" value="<?php echo $appId ?>"/>
</div> 
<div class="alert alert-success alert-dismissible app-notify" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <strong>Success!</strong> <?php _e('Your application is updated.') ?>
</div>
</div>
<script type="text/javascript">
    var loanSlider;

    function fieldOnChange(e) {
        if ($(e).valid() == true) {
            $(e).closest('.um-field-area').find('.fa-input').css({display: 'block'});
        } else {
            $(e).closest('.um-field-area').find('.fa-input').css({display: 'none'});
        }
    }

    function abnChange(e) {
        var q = $(e).val();
        if (q.length) {
            $('.abn-search-link').hide();
            $('.loadding').show();
            $('.abn-wapepr .error').hide();
            $.ajax({
                type: 'POST',
                url: ajaxurl,
                data: {action: 'get_abn_info', q: q},
                success: function(resp) {
                    $('.loadding').hide();
                    if (!resp.errno) {
                        $('.abn-wapepr .abn-val-name').html(resp.bussiness.name);
                        $('.abn-wapepr .abn-val-date').html(resp.bussiness.effectiveFrom);
                        $('.abn-wapepr .abn-val-state').html(resp.bussiness.stateName);
                        $('.abn-wapepr .app-abn-info').show();
                        $('.abn-wapepr .error').hide();
                    } else {
                        $('.abn-wapepr .app-abn-info').hide();
                        $('.abn-wapepr .error').show();
                    }
                }
            });
        }
    }

    jQuery(document).ready(function($) {
        loanSlider = new LoanExpresSlider({'max': 1000000, 'min': 5000, 'step': 5000, 'start': <?php echo intval($loan_amount); ?>});
        loanSlider.updatePrice = function() {
            this.slided = true;
            var val = this.loanSlider.noUiSlider.get();
            $('#loan_amount').val(this.formatCurrency(val));
        };
        loanSlider.initialize();
        $('#loan_amount').change(function() {
            var amount = $(this).val();
            var number = amount.replace(/[^0-9\.]+/g, "");
            if ($.isNumeric(number)) {
                if (number < 5000 && number > 1000000) {
                    alert('Please enter loan amount in range from $5,000 to $1,0000,000');
                } else {
                    loanSlider.val(number);
                }
                $(this).val(loanSlider.formatCurrency(number));
            } else {
                alert('Please enter a number');
            }

        });

        //$('#loan_customer_phone').mask('(00) 0000 0000');
        $('#loan_dob').datepicker({
            format: 'dd/mm/yyyy'
        });
        $('#loan_dob').mask("00/00/0000", {placeholder: "__/__/____"});
        $('.um-form form:first-child').validate();
        $('.um-form')
        $('#um_app_submit').click(function() {
            if ($('.um-form form:first-child').valid()) {
                $('.loaderx').show();
                var formData = new FormData($('.um-form form:first-child')[0]);
                formData.append('action', 'um_save_app');
                formData.set('loan_amount', loanSlider.val());
                $.ajax({
                    url: ajaxurl,
                    type: 'POST',
                    data: formData,
                    cache: false,
                    contentType: false,
                    processData: false,
                    success: function(resp) {
                        $('.loaderx').hide();
                        if (!resp.errno) {
                            $('.app-notify').show();
                        }
                    }
                })
            } else {
                alert('Please valid all field required');
            }
        });
    });
</script>