<?php
/**
 * OnlineBiz Software Solution
 * 
 * @project lendclick.com.au
 * @version 0.0.1
 * @encoding UTF-8
 * @author Joe Vu<joe@onlinebizsoft.com>
 * @see http://onlinebizsoft.com
 * @copyright (c) 2017 , OnlineBiz Software Solution
 * 
 * Create at: Dec 7, 2017 11:24:01 AM
 */
global $post;
$app_info = get_post_meta($post->ID, 'app_info', true);
if (is_array($app_info)) {
    extract($app_info);
}
?>
<style type="text/css">
    #render_metabox_application{
        width: 500px
    }
    #render_metabox_application td{
        padding: 5px 0;
    }
    #render_metabox_application td .full-width{
        width: 100%;
    }
    .noUi-base{
        background-color: #d6d6d6;
    }
    .noUi-horizontal .noUi-handle{
        background: #23a755;
        width: 29px;
        height: 29px;
        cursor: pointer;
        border-radius: 50%;
        border:none !important;
        box-shadow: none !important;
        top: -10px;
    }
    .noUi-handle:after, .noUi-handle:before{
        display: none;
    }
    .noUi-horizontal{
        height: 10px;
    }
    .noUi-connect{
        background-color: #238247;
    }
    .loan-slider-wapper{
        position: relative;
        height: 32px;
        color:#a5a5a5;
        font-size: 12px;
    }
    .loan-slider-wapper .limit{
        position: absolute;
        bottom: 0;
    }
    .loan-slider-wapper .loan-max{
        right: 0;
    }
    .loan-slider-wapper .loan-min{
        left: 0;
    }
</style>
<table id="render_metabox_application"> 
    <tr>
        <td><?php _e('Full Name:') ?></td>
        <td><input type="text" class="form-control full-width" id="loan_customer_name" name="app[loan_customer_name]" value="<?php echo isset($loan_customer_name) ? $loan_customer_name : '' ?>"/></td>
    </tr>
    <tr>
        <td><?php _e('Birthday:') ?></td>
        <td><input type="text" placeholder="__/__/____" maxlength="10" class="form-control full-width" id="loan_dob" name="app[loan_dob]" value="<?php echo isset($loan_dob) ? $loan_dob : '' ?>"/></td>
    </tr>
    <tr>
        <td><?php _e('Email address:') ?></td>
        <td><input type="email" class="form-control full-width" id="loan_customer_email" name="app[loan_customer_email]" value="<?php echo isset($loan_customer_email) ? $loan_customer_email : '' ?>"/></td>
    </tr>
    <tr>
        <td><?php _e('Phone:') ?></td>
        <td><input type="tel" class="form-control full-width" id="loan_customer_phone" name="app[loan_customer_phone]" value="<?php echo isset($loan_customer_phone) ? $loan_customer_phone : '' ?>"/></td>
    </tr>
    <tr>
        <td><?php _e('ABN:') ?></td>
        <td><input type="text" class="form-control full-width" id="loan_abn" name="app[loan_abn]" value="<?php echo isset($loan_abn) ? $loan_abn : '' ?>"/></td>
    </tr>
    <tr>
        <td><?php _e('Business Name:') ?></td>
        <td><input type="text" class="form-control full-width" id="loan_customer_business" name="app[loan_customer_business]" value="<?php echo isset($loan_customer_business) ? $loan_customer_business : '' ?>"/></td>
    </tr>
    <tr>
        <td><?php _e('Industry') ?></td>
        <td>
            <?php
            echo $this->getIndustrySelect('loan_industry', 'app[loan_industry]', isset($loan_industry) ? $loan_industry : '', array(
                'class' => 'form-control full-width'
            ));
            ?>
    </tr>
    <tr>
        <td><?php _e('Driving License Number') ?></td>
        <td><input type="text" class="form-control full-width" id="loan_driving_license_number" name="app[loan_driving_license_number]" value="<?php echo isset($loan_driving_license_number) ? $loan_driving_license_number : '' ?>"/></td>
    </tr>
    <tr>
        <td><?php _e('Loan Amount(USD)') ?></td>
        <td>
            <div class="loan-slider-wapper">
                <div id="loan-slider"></div>
                <span class="loan-min limit">$5,000</span>
                <span class="loan-max limit">$1,000,000</span>
            </div>
            <input type="text" class="form-control full-width"  id="loan_amount" name="app[loan_amount]" value="<?php echo isset($loan_amount) ? (is_numeric($loan_amount) ? sprintf('$%s', number_format($loan_amount)) : $loan_amount) : '' ?>"/></td>
    </tr>
    <tr>
        <td><?php _e('Loan Term (Months):') ?></td>
        <?php
        $loan_terms = isset($loan_terms) ? $loan_terms : '';
        $termCollection = array('Any', '3-6', '6-12', '12-24', '24+');
        ?>
        <td><select name="app[loan_terms]">
                <?php foreach ($termCollection as $termName): ?>
                    <?php if ($termName == $loan_terms): ?>
                        <option value="<?php echo $termName ?>" selected=""><?php echo $termName ?></option>
                    <?php else: ?>
                        <option value="<?php echo $termName ?>"><?php echo $termName ?></option>
                    <?php endif ?>
                <?php endforeach; ?>
            </select></td>
    </tr>
    <tr>
        <td><?php _e('Loan Products:') ?></td>
        <?php
        $selected = isset($loan_products) ? explode(',', $loan_products) : array();
        $collection = array('Unsecured Business Loans', 'Invoice Finance', 'Line of Credit / Trade Finance', 'Equipment Finance', 'Vehicle Finance', 'Property Development Finance');
        ?>
        <td><select name="app[loan_products][]" multiple="" class="form-control full-width">
                <?php
                foreach ($collection as $k => $productName):
                    ?>
                    <?php if (in_array($k, $selected)): ?>
                        <option value="<?php echo $k ?>" selected=""><?php echo $productName ?></option>
                    <?php else: ?>
                        <option value="<?php echo $k ?>"><?php echo $productName ?></option>
                    <?php endif; ?>
                    <?php
                endforeach;
                ?>
            </select></td>
    </tr>
    <tr>
        <td><?php _e('Time of business operating?') ?></td>
        <td>
            <?php
            $selected = isset($time_of_business_operating) ? $time_of_business_operating : '';
            $collection = array('Less than 3 months', '3-5 months', '6-12 months', '1-2 years', '3-5 years', 'More than 5 years');
            ?>
            <select id="time_of_business_operating" name="app[time_of_business_operating]" class="form-control full-width">
                <?php
                foreach ($collection as $k => $timeName):
                    ?>
                    <?php if ($selected == $timeName): ?>
                        <option value="<?php echo $timeName ?>" selected=""><?php echo $timeName ?></option>
                    <?php else: ?>
                        <option value="<?php echo $timeName ?>"><?php echo $timeName ?></option>
                    <?php endif; ?>
                    <?php
                endforeach;
                ?>
            </select>
        </td>
    </tr>
    <tr>
        <td><?php _e('Monthly revenue? (average over past 6 months)') ?></td>
        <td>
            <?php
            $selected = isset($loan_average_revenue) ? $loan_average_revenue : '';
            $collection = array('$0 - $10k', '$10k - $25k', '$100k - $250k', '$250k - $500k', '$500k+');
            ?>
            <select id="loan_average_revenue" name="app[loan_average_revenue]" class="form-control full-width">
                <?php
                foreach ($collection as $k => $revenueName):
                    ?>
                    <?php if ($selected == $revenueName): ?>
                        <option value="<?php echo $revenueName ?>" selected=""><?php echo $revenueName ?></option>
                    <?php else: ?>
                        <option value="<?php echo $revenueName ?>"><?php echo $revenueName ?></option>
                    <?php endif; ?>
                    <?php
                endforeach;
                ?>
            </select>
    </tr>
    <tr>
        <td><?php _e('Additional contact number:') ?></td>
        <td><input type="text" class="form-control full-width" id="business_phone_number" name="app[business_phone_number]" value="<?php echo isset($business_phone_number) ? $business_phone_number : '' ?>"/></td>
    </tr>
    <tr>
        <td><?php _e('Best time to call:') ?></td>
        <td><input type="text" class="form-control full-width" id="best_time_to_reach" name="app[best_time_to_reach]" value="<?php echo isset($best_time_to_reach) ? $best_time_to_reach : '' ?>"/></td>
    </tr>
</table>
<script type="text/javascript">
    var loanSlider;
    jQuery(document).ready(function($) {
        loanSlider = new LoanExpresSlider({'max': 1000000, 'min': 5000, 'step': 5000, 'start': <?php echo intval($loan_amount);?>});
        loanSlider.updatePrice = function(){
            this.slided = true;
            var val = this.loanSlider.noUiSlider.get();
            $('#loan_amount').val(this.formatCurrency(val));
        };
        loanSlider.initialize();
        $('#loan_amount').change(function(){
            var amount = $(this).val();
            var number = amount.replace(/[^0-9\.]+/g,"");
            if($.isNumeric(number)){
                if(number < 5000 && number > 1000000){
                    alert('Please enter loan amount in range from $5,000 to $1,0000,000');
                }else{
                    loanSlider.val(number);
                }
                $(this).val(loanSlider.formatCurrency(number));
            }else{
                alert('Please enter a number');
            }
            
        });
        
        $('[type="tel"]').mask('(00) 0000 0000');
        $('#loan_dob').mask("00/00/0000", {placeholder: "__/__/____"});
    });
</script>
