<?php
/**
 * OnlineBiz Software Solution
 * 
 * @project lendclick.com.au
 * @version 0.0.1
 * @encoding UTF-8
 * @author Joe Vu<joe@onlinebizsoft.com>
 * @see http://onlinebizsoft.com
 * @copyright (c) 2017 , OnlineBiz Software Solution
 * 
 * Create at: Dec 7, 2017 11:24:01 AM
 */
global $post;
$lender = false;
$lender_email = get_post_meta($post->ID, 'lender_email', true);
$lender_phone = get_post_meta($post->ID, 'lender_phone', true);
$lender_term = get_post_meta($post->ID, 'lender_term', true);
$lender_products = get_post_meta($post->ID, 'lender_products', true);
$lender_amount_min = get_post_meta($post->ID, 'lender_amount_min', true);
$lender_amount_max = get_post_meta($post->ID, 'lender_amount_max', true);
$lender_webhook = get_post_meta($post->ID, 'lender_webhook', true);
?>
<style type="text/css">
    #render_metabox_lender{
        width: 500px
    }
    #render_metabox_lender td{
        padding: 5px 0;
    }
    #render_metabox_lender td .full-width{
        width: 100%;
    }
</style>
<table id="render_metabox_lender"> 
    <tr>
        <td><?php _e('Email address:') ?></td>
        <td><input type="email" class="form-control full-width" id="email" name="lender_email" value="<?php echo $lender_email ?>"/></td>
    </tr>
    <tr>
        <td><?php _e('Phone:') ?></td>
        <td><input type="text" class="form-control full-width" id="phone" name="lender_phone" value="<?php echo $lender_phone ?>"/></td>
    </tr>
    <tr>
        <td><?php _e('Loan Term (Months):') ?></td>
        <?php
        $termCollection = array('Any', '3-6','6-12','12-24','24+');
        ?>
        <td><select name="lender_term">
                <?php foreach ($termCollection as $termName):?>
                    <?php if($termName == $lender_term):?>
                        <option value="<?php echo $termName ?>" selected=""><?php echo $termName ?></option>
                    <?php else:?>
                        <option value="<?php echo $termName ?>"><?php echo $termName ?></option>
                    <?php endif?>
                <?php endforeach;?>
            </select></td>
    </tr>
    <tr>
        <td><?php _e('Loan Products:') ?></td>
        <?php
        $selected = $lender_products;
        $collection = array('Unsecured Business Loans', 'Invoice Finance', 'Line of Credit / Trade Finance', 'Equipment Finance', 'Vehicle Finance', 'Property Development Finance');
        ?>
        <td><select name="lender_products[]" multiple="" class="form-control full-width">
                <?php
                foreach ($collection as $k => $productName):
                    ?>
                    <?php if(in_array($k, $selected)): ?>
                    <option value="<?php echo $k ?>" selected=""><?php echo $productName ?></option>
                    <?php else: ?>
                    <option value="<?php echo $k ?>"><?php echo $productName ?></option>
                    <?php endif; ?>
                    <?php
                endforeach;
                ?>
            </select></td>
    </tr>
    <tr>
        <td><?php _e('Loan Amount (USD):') ?></td>
        <td>
            Min:
            <input type="text" size="5" name="lender_amount_min" value="<?php echo $lender_amount_min ? $lender_amount_min: '0' ?>"/>
            &nbsp;&nbsp;&nbsp;
            Max:
            <input type="text" size="5" name="lender_amount_max" value="<?php echo $lender_amount_max ? $lender_amount_max: '1000000000' ?>"/>
        </td>
    </tr>
    <tr>
        <td><?php _e('Webhook :') ?></td>
        <td><input type="text" class="form-control full-width" id="webhook" name="lender_webhook" value="<?php echo $lender_webhook ?>"/></td>
    </tr>
</table>
