<?php
/**
 * OnlineBiz Software Solution
 * 
 * @project lendclick.com.au
 * @version 0.0.1
 * @encoding UTF-8
 * @author Joe Vu<joe@onlinebizsoft.com>
 * @see http://onlinebizsoft.com
 * @copyright (c) 2017 , OnlineBiz Software Solution
 * 
 * Create at: Nov 30, 2017 11:24:47 AM
 */
?>
<div class="cloanexpress">
    <div class="loan-main">
        <div class="loan-loader">
            <p><i class="glyphicon glyphicon-refresh"></i> <?php _e('Please wait...') ?></p>
        </div>
        <ol class="loan-indicators">
            <li data-step="#step1" onclick="loanExpress.step(this)" class="active">1</li>
            <li data-step="#step2" onclick="loanExpress.step(this)">2</li>
            <li data-step="#step3" onclick="loanExpress.step(this)">3</li>
            <li data-step="#step4" onclick="loanExpress.step(this)">4</li>
        </ol>
        <div id="step1" class="step" data-valid="false" data-indicator="false">
            <div class="slider-wapper">
                <h3><?php _e('Choose Loan Amount') ?></h3>
                <div id="howmuch-num">$5,000-$1,000,000</div>
                <div class="loan-slider-wapper">
                    <div id="loan-slider"></div>
                    <span class="loan-min limit">$5,000</span>
                    <span class="loan-max limit">$1,000,000</span>
                    <span id="select-amount-error" style="display: none"><?php _e('Please Choose Loan Amount') ?></span>
                </div>
                <a class="btn btn-success btn-lg start-steps" id="main-button" href="javascript:void()" onclick="loanExpress.stepLoanSlider(this)"  role="button" style="box-shadow: rgba(0, 0, 0, 0.46) 0px 4px 8px;">Check Eligibility</a>
            </div>
        </div>
        <div id="step2" class="step" data-valid="false" data-indicator="true">
            <h2><?php _e('Time of business operating?') ?></h2>
            <div class="row loan-time-of-business-operating">
                <div class="text-center answers-section" style=" margin-top: 28px; ">
                    <div class="col-md-4">
                        <a class="btn btn-default btn-lg step-buttons" data-val="Less than 3 months" onclick="loanExpress.stepTimeOfBusinessOperating(this)">Less than 3 months</a>
                    </div>
                    <div class="col-md-4">
                        <a class="btn btn-default btn-lg step-buttons" data-val="3-5 months" onclick="loanExpress.stepTimeOfBusinessOperating(this)">3-5 months</a>
                    </div>
                    <div class="col-md-4">
                        <a class="btn btn-default btn-lg step-buttons" data-val="6-12 months" onclick="loanExpress.stepTimeOfBusinessOperating(this)">6-12 months</a>
                    </div>
                    <div class="col-md-4">
                        <a class="btn btn-default btn-lg step-buttons" data-val="1-2 years" onclick="loanExpress.stepTimeOfBusinessOperating(this)">1-2 years</a>
                    </div>
                    <div class="col-md-4">
                        <a class="btn btn-default btn-lg step-buttons" data-val="3-5 years" onclick="loanExpress.stepTimeOfBusinessOperating(this)">3-5 years</a>
                    </div>
                    <div class="col-md-4">
                        <a class="btn btn-default btn-lg step-buttons" data-val="<?php _e('More than 5 years') ?>" onclick="loanExpress.stepTimeOfBusinessOperating(this)">More than 5 years</a>
                    </div>
                </div>
            </div>
        </div>
        <div id="step3" class="step" data-valid="false" data-indicator="true">
            <h2><?php _e('Monthly revenue?') ?> <br/><small><?php _e('(average over past 6 months)') ?></small></h2>
            <div class="row loan-monthly-revenue">
                <div class="text-center answers-section" style=" margin-top: 28px; ">
                    <div class="col-md-4">
                        <a class="btn btn-default btn-lg step-buttons" data-val="$0 - $10k" onclick="loanExpress.stepLoanAverageRevenue(this)">$0 - $10k</a>
                    </div>
                    <div class="col-md-4">
                        <a class="btn btn-default btn-lg step-buttons" data-val="$10k - $25k" onclick="loanExpress.stepLoanAverageRevenue(this)">$10k - $25k</a>
                    </div>
                    <div class="col-md-4">
                        <a class="btn btn-default btn-lg step-buttons" data-val="$100k - $250k" onclick="loanExpress.stepLoanAverageRevenue(this)">$100k - $250k</a>
                    </div>
                    <div class="col-md-4">
                        <a class="btn btn-default btn-lg step-buttons" data-val="$250k - $500k" onclick="loanExpress.stepLoanAverageRevenue(this)">$250k - $500k</a>
                    </div>
                    <div class="col-md-4">
                        <a class="btn btn-default btn-lg step-buttons" data-val="$500k+" onclick="loanExpress.stepLoanAverageRevenue(this)">$500k+</a>
                    </div>
                </div>
            </div>
        </div>
        <div id="step4" class="step" data-valid="false" data-indicator="true">
            <h2 class="offers-now">
                <span class="leadbox-title"><?php _e('We found relevant lenders for you!') ?></span>
                <?php _e('Get Your Loan Offers Now') ?>
            </h2>
            <div class="loan-offers">
                <form id="loan-offers-frm" onsubmit="return false;">
                    <div class="loan-form-field">
                        <label><?php _e('Full name') ?></label><br>
                        <span class="wpcf7-form-control-wrap">
                            <input type="text" name="name" minlength="2" size="40" class="wpcf7-form-control wpcf7-text  loan-field" placeholder="Full name" required=""/>
                        </span>
                    </div>
                    <div class="loan-form-field">
                        <label><?php _e('Email Address') ?></label><br>
                        <span class="wpcf7-form-control-wrap"><input type="text" name="email" value="" size="40" class="wpcf7-form-control wpcf7-text  loan-field" placeholder="Email Address" required=""/></span>
                    </div>
                    <div class="loan-form-field">
                        <label><?php _e('Phone') ?></label><br>
                        <span class="wpcf7-form-control-wrap"><input type="tel" name="phone" value="" size="40" class="wpcf7-form-control wpcf7-text loan-field" placeholder="Phone" required=""/></span>
                    </div>
                    <div class="loan-form-field">
                        <label><?php _e('Business Name') ?></label><br>
                        <span class="wpcf7-form-control-wrap"><input type="text" name="business" value="" size="40" class="wpcf7-form-control wpcf7-text loan-field" placeholder="Business Name" required=""/></span>
                    </div>
                    <div class="loan-form-field-checkbox">
                        <span class="wpcf7-form-control-wrap">
                            <span class="wpcf7-form-control wpcf7-checkbox loan-field">
                                <span class="wpcf7-list-item first last">
                                    <input type="checkbox" name="term_condition" value="<?php _e('I have reviewed, understand and consent to the') ?>">
                                    <span class="wpcf7-list-item-label"><?php _e('I have reviewed, understand and consent to the') ?></span></span></span></span><a class="privacy-policy" target="_blank" href="privacy-policy/">Privacy Policy</a>
                    </div>
                    <div class="loan-form-field">
                        <div class="submit-left">
                            <span class="encryption"><?php _e('We use 256-bit encryption to protect your information') ?></span>
                        </div>
                        <div class="submit-right2">
                            <input type="submit" onclick="loanExpress.stepLoanOffers(this)" value="<?php _e('Get Offers Now') ?>" class="wpcf7-form-control wpcf7-submit loan-field">
                            <span class="ajax-loader"></span>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div id="step5" class="step" data-valid="false" data-indicator="false">
            <h2><?php _e('What is your Birth Date?') ?></h2>
            <div class="loan-dob">
                <form id="dob-frm" onsubmit="return false;">
                    <div class="row" style="padding: 10px 0">
                        <div class="col-md-4 col-sm-4 col-xs-4">
                            <div class="form-group input">
                                <select required="" class="form-control step-select" id="birth_day" name="birth_day">
                                    <option value="">Day</option>
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                    <option value="5">5</option>
                                    <option value="6">6</option>
                                    <option value="7">7</option>
                                    <option value="8">8</option>
                                    <option value="9">9</option>
                                    <option value="10">10</option>
                                    <option value="11">11</option>
                                    <option value="12">12</option>
                                    <option value="13">13</option>
                                    <option value="14">14</option>
                                    <option value="15">15</option>
                                    <option value="16">16</option>
                                    <option value="17">17</option>
                                    <option value="18">18</option>
                                    <option value="19">19</option>
                                    <option value="20">20</option>
                                    <option value="21">21</option>
                                    <option value="22">22</option>
                                    <option value="23">23</option>
                                    <option value="24">24</option>
                                    <option value="25">25</option>
                                    <option value="26">26</option>
                                    <option value="27">27</option>
                                    <option value="28">28</option>
                                    <option value="29">29</option>
                                    <option value="30">30</option>
                                    <option value="31">31</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-4">
                            <div class="form-group input">
                                <select class="form-control step-select" id="birth_month" name="birth_month" required="">
                                    <option value="">Month</option>
                                    <option value="1">January</option>
                                    <option value="2">February</option>
                                    <option value="3">March</option>
                                    <option value="4">April</option>
                                    <option value="5">May</option>
                                    <option value="6">June</option>
                                    <option value="7">July</option>
                                    <option value="8">August</option>
                                    <option value="9">September</option>
                                    <option value="10">October</option>
                                    <option value="11">November</option>
                                    <option value="12">December</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4 col-sm-4 col-xs-4">
                            <div class="form-group input">
                                <select class="form-control step-select" id="birth_year" name="birth_year" required="">
                                    <option value="">Year</option>
                                    <option value="1999">1999</option>
                                    <option value="1998">1998</option>
                                    <option value="1997">1997</option>
                                    <option value="1996">1996</option>
                                    <option value="1995">1995</option>
                                    <option value="1994">1994</option>
                                    <option value="1993">1993</option>
                                    <option value="1992">1992</option>
                                    <option value="1991">1991</option>
                                    <option value="1990">1990</option>
                                    <option value="1989">1989</option>
                                    <option value="1988">1988</option>
                                    <option value="1987">1987</option>
                                    <option value="1986">1986</option>
                                    <option value="1985">1985</option>
                                    <option value="1984">1984</option>
                                    <option value="1983">1983</option>
                                    <option value="1982">1982</option>
                                    <option value="1981">1981</option>
                                    <option value="1980">1980</option>
                                    <option value="1979">1979</option>
                                    <option value="1978">1978</option>
                                    <option value="1977">1977</option>
                                    <option value="1976">1976</option>
                                    <option value="1975">1975</option>
                                    <option value="1974">1974</option>
                                    <option value="1973">1973</option>
                                    <option value="1972">1972</option>
                                    <option value="1971">1971</option>
                                    <option value="1970">1970</option>
                                    <option value="1969">1969</option>
                                    <option value="1968">1968</option>
                                    <option value="1967">1967</option>
                                    <option value="1966">1966</option>
                                    <option value="1965">1965</option>
                                    <option value="1964">1964</option>
                                    <option value="1963">1963</option>
                                    <option value="1962">1962</option>
                                    <option value="1961">1961</option>
                                    <option value="1960">1960</option>
                                    <option value="1959">1959</option>
                                    <option value="1958">1958</option>
                                    <option value="1957">1957</option>
                                    <option value="1956">1956</option>
                                    <option value="1955">1955</option>
                                    <option value="1954">1954</option>
                                    <option value="1953">1953</option>
                                    <option value="1952">1952</option>
                                    <option value="1951">1951</option>
                                    <option value="1950">1950</option>
                                    <option value="1949">1949</option>
                                    <option value="1948">1948</option>
                                    <option value="1947">1947</option>
                                    <option value="1946">1946</option>
                                    <option value="1945">1945</option>
                                    <option value="1944">1944</option>
                                    <option value="1943">1943</option>
                                    <option value="1942">1942</option>
                                    <option value="1941">1941</option>
                                    <option value="1940">1940</option>
                                    <option value="1939">1939</option>
                                    <option value="1938">1938</option>
                                    <option value="1937">1937</option>
                                    <option value="1936">1936</option>
                                    <option value="1935">1935</option>
                                    <option value="1934">1934</option>
                                    <option value="1933">1933</option>
                                    <option value="1932">1932</option>
                                    <option value="1931">1931</option>
                                    <option value="1930">1930</option>
                                    <option value="1929">1929</option>
                                    <option value="1928">1928</option>
                                    <option value="1927">1927</option>
                                </select>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <span id="birth_date_error_text" class="error error_input_text full-rounded-error"><?php _e('Please select your birth date') ?></span>
                        <div class="btn-next">
                            <a class="btn btn-default btn-sm step-buttons" role="button" href="javascript:void()" onclick="loanExpress.stepDob(this)"  data-slide="next">Next <i class="fa fa-chevron-right" aria-hidden="true"></i></a>
                        </div>
                    </div>

                </form>
            </div>
        </div>
        <div id="step6" class="step" data-valid="false" data-indicator="false">
            <h2><?php _e('Choose loan products') ?></h2>
            <div class="loan-products">
                <div class="row">
                    <div class="text-center">
                        <div class="col-md-6">
                            <a class="btn btn-default btn-lg step-buttons active" data-val="0" onclick="loanExpress.selectProduct(this)"><?php _e('Unsecured Business Loans') ?></a>
                        </div>
                        <div class="col-md-6">
                            <a class="btn btn-default btn-lg step-buttons active" data-val="1" onclick="loanExpress.selectProduct(this)"><?php _e('Invoice Finance') ?></a>
                        </div>
                        <div class="col-md-6">
                            <a class="btn btn-default btn-lg step-buttons active" data-val="2" onclick="loanExpress.selectProduct(this)"><?php _e('Line of Credit / Trade Finance') ?></a>
                        </div>
                        <div class="col-md-6">
                            <a class="btn btn-default btn-lg step-buttons active" data-val="3" onclick="loanExpress.selectProduct(this)"><?php _e('Equipment Finance') ?></a>
                        </div>
                        <div class="col-md-6">
                            <a class="btn btn-default btn-lg step-buttons active" data-val="4" onclick="loanExpress.selectProduct(this)"><?php _e('Vehicle Finance') ?></a>
                        </div>
                        <div class="col-md-6">
                            <a class="btn btn-default btn-lg step-buttons active" data-val="5" onclick="loanExpress.selectProduct(this)"><?php _e('Property Development Finance') ?></a>
                        </div>
                    </div>

                </div>
                <div class="col-md-6 btn-next" style="margin: 30px auto; float: none">
                    <a class="btn btn-default btn-sm step-buttons" role="button" href="javascript:void()" onclick="loanExpress.stepLoanProducts(this)"  data-slide="next">Next <i class="fa fa-chevron-right" aria-hidden="true"></i></a>
                </div>
            </div>
            <div class="col-lg-12">
                <a class="back-arrow" href="javascript:void()" data-step="#step5" onclick="loanExpress.step(this)">
                    <i class="fa fa-chevron-left" aria-hidden="true"></i> Back</a>
            </div>
        </div>
        <div id="step7" class="step" data-valid="false" data-indicator="false">
            <h2><?php _e('Select Term (Month)') ?></h2>
            <div class="loan-terms">
                <div class="row">
                    <div class="text-center answers-section" style=" margin-top: 28px; ">
                        <div class="col-md-4">
                            <a class="btn btn-default btn-lg step-buttons" data-val="Any" onclick="loanExpress.stepLoanTerm(this)">Any</a>
                        </div>
                        <div class="col-md-4">
                            <a class="btn btn-default btn-lg step-buttons" data-val="3-6" onclick="loanExpress.stepLoanTerm(this)">3-6</a>
                        </div>
                        <div class="col-md-4">
                            <a class="btn btn-default btn-lg step-buttons" data-val="6-12" onclick="loanExpress.stepLoanTerm(this)">6-12</a>
                        </div>
                        <div class="col-md-4">
                            <a class="btn btn-default btn-lg step-buttons" data-val="12-24" onclick="loanExpress.stepLoanTerm(this)">12-24</a>
                        </div>
                        <div class="col-md-4">
                            <a class="btn btn-default btn-lg step-buttons" data-val="24+" onclick="loanExpress.stepLoanTerm(this)">24+</a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <a class="back-arrow" href="javascript:void()" data-step="#step6" onclick="loanExpress.step(this)">
                    <i class="fa fa-chevron-left" aria-hidden="true"></i> Back</a>
            </div>
        </div>
        <div id="step8" class="step" data-valid="false" data-indicator="false">
            <h2 class="small-margin-top">
                Choose your<br><b>Industry Type</b>
            </h2>
            <div class="loan-industry">
                <form id="industry-frm">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <div class="form-group input">
                                <?php
                                echo $this->getIndustrySelect('industry_ID', 'industry_ID', '', array(
                                    'class' => 'form-control step-select'
                                ));
                                ?>
                                <div>
                                    <span id="industry_name_error_text" class="error_input_text"><?php _e('Please select an industry') ?></span>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-offset-4 col-md-4">
                            <a class="btn btn-default btn-sm step-buttons" href="javascript:void()" onclick="loanExpress.stepLoanIndustry(this)">Next <i class="fa fa-chevron-right" aria-hidden="true"></i></a>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-12">
                <a class="back-arrow" href="javascript:void()" data-step="#step7" onclick="loanExpress.step(this)">
                    <i class="fa fa-chevron-left" aria-hidden="true"></i> Back</a>
            </div>
        </div>
        <div id="step9" class="step" data-valid="false" data-indicator="false">
            <h2><?php _e('Driving license number') ?></h2>
            <div class="loan-driving-license-number">
                <div class="text-center answers-section answers-small-margin">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <div class="form-group input">
                                <input class="form-control step-input" id="driver_license" name="driver_license" type="text" maxlength="10" placeholder="<?php _e('Driver License Number') ?>">
                                <div>
                                    <span id="driver_license_error_text" class="error_input_text" style="display: none;"><?php _e('Please enter your driver\'s license number') ?></span>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-offset-4 col-md-4">
                        <a class="btn btn-default btn-sm step-buttons" onclick="loanExpress.stepLoanDrivingLicenseNumber(this)" href="javascript:void()">Next <i class="fa fa-chevron-right" aria-hidden="true"></i></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <a class="back-arrow" href="javascript:void()" data-step="#step8" onclick="loanExpress.step(this)">
                    <i class="fa fa-chevron-left" aria-hidden="true"></i> Back</a>
            </div>
        </div>
        <div id="step10" class="step" data-valid="false" data-indicator="false">
            <h2 class="small-margin-top">What is your<br><b>ABN</b></h2>
            <div class="loan-abn">
                <div class="abn-loader">
                    <p><i class="glyphicon glyphicon-refresh abn-loader-processing"></i> <?php _e('Validating ABN. please wait...') ?></p>
                </div>
                <div class="text-center answers-section answers-small-margin">
                    <div class="row">
                        <div class="col-md-8 col-md-offset-2">
                            <div class="form-group input abn-field-container">
                                <input maxlength="11" class="form-control step-input" id="abn_num" name="abn_num" type="text" placeholder="Enter your ABN" data-valid="false" onchange="loanExpress.verifyAbn(this)">
                                <div>
                                    <span id="abn_num_error_text" class="error_input_text"><?php _e('Enter a valid ABN number') ?><br>or <a onclick="loanExpress.stepAbn(this, true)" id="skip-abn" data-slide="next" href="javascript:void()" style="text-decoration:underline;color:#000;" skip="">Skip</a></span>
                                </div>
                                <span class="abn-search-link"><?php _e('Not sure? Try search for your ABN') ?> <a style="text-decoration:underline" href="http://abr.business.gov.au" target="_blank">here</a></span>
                            </div>
                        </div>
                        <div class="abn-info col-md-8 col-md-offset-2">
                            <div class="col-md-6">
                                <span class="abn-title"><?php _e('Business Legal Name') ?></span>
                                <span class="abn-details abn-legal-name"></span>
                            </div>
                            <div class="col-md-6">
                                <span class="abn-title"><?php _e('Registration Date') ?></span>
                                <span class="abn-details abn-reg-date">1999-11-01</span>
                            </div>
                            <br>
                        </div>
                        <div class="col-md-offset-4 col-md-4">
                            <a class="btn btn-default btn-sm step-buttons" role="button" href="javascript:void()" onclick="loanExpress.stepAbn(this, false)">Next <i class="fa fa-chevron-right" aria-hidden="true"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <a class="back-arrow" href="javascript:void()" data-step="#step9" onclick="loanExpress.step(this)">
                    <i class="fa fa-chevron-left" aria-hidden="true"></i> Back</a>
            </div>
        </div>
<!--        <div id="step11" class="step" data-valid="false" data-indicator="false">
            <h2 class="small-margin-top"><?php _e('Select up to 3 lenders and click "Proceed"') ?></h2>
            <div class="loan-lenders">
                <div class="lender-loader">
                    <p><i class="glyphicon glyphicon-refresh abn-loader-processing"></i> <?php _e('Please wait...') ?></p>
                </div>
                <div class="lender-main"></div>
                <div class="col-md-offset-4 col-md-4 process-btn" style="display: none">
                    <a class="btn btn-default btn-sm step-buttons" role="button" href="javascript:void()" onclick="loanExpress.stepLenders(this)">Proceed <i class="fa fa-chevron-right" aria-hidden="true"></i></a>
                </div>
                <div class="col-md-offset-4 col-md-4 fail-btn" style="display: none">
                    <a class="btn btn-default btn-sm step-buttons" role="button" href="javascript:void()" data-step="#step10" onclick="loanExpress.step(this)"><i class="fa fa-chevron-left" aria-hidden="true"></i> Back</a>
                </div>
            </div>
             Modal 
            <div class="modal fade in" role="dialog" style="position: absolute; background-color: rgba(0,0,0,0.7)">
                <div class="modal-dialog">
                     Modal content
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Disclaimer</h4>
                        </div>
                        <div class="modal-body">
                            <p>Lend Click provides you with easy online application services. Lend Click is not a loan provider or other funding provider and does not provide actual loans or any kind of advice. By providing the application information and selecting third party lender/s, you authorize us to share your application information with those third party lenders. When applying for a loan from a third party lender, you should disclose all relevant financial information, including whether you have any outstanding loans or have applied to receive any loans from another third party lender. Approval of an actual loan from the third party lender is subject to a separate assessment process by the third party lender and the loan is subject to the third party lender's terms and conditions.</p>
                        </div>
                        <div class="modal-footer" style="text-align: center">
                            <div id="disclaimer-check-div"><input style="float:left;margin-right:5px;" type="checkbox" id="disclaimer-check" name="disclaimer-check"> I understand and agree</div>
                            <br/>
                            <button type="button" class="modal-ok btn btn-sm btn-success" onclick="loanExpress.stepAgree(this)">Agree</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>-->
        <div id="step11" class="step" data-valid="false" data-indicator="false">
            <h2 class="modal-title"><?php _e('Wait, one last thing before your chosen lenders call you!') ?></h2>
            <div class="loan-additional">
                <div class="additional-loader">
                    <p><i class="glyphicon glyphicon-refresh abn-loader-processing"></i> <?php _e('Submitting application to lenders....') ?></p>
                </div>
                <div class="form-group">
                    <label class="control-label"><?php _e('Additional contact number') ?></label>
                    <input type="tel" class="form-control business_field" name="business_phone_number" maxlength="15">
                    <label class="control-label"><?php _e('Best time to call') ?></label>
                    <input type="text" class="form-control business_field" name="best_time_to_reach" maxlength="250">
                    <br/>
                    <div class="bottom-panel text-center col-lg-12">
                        <button type="button" id="additional-fields-save" class="btn-sm  btn-success " onclick="loanExpress.stepFinish(this)">Finish</button>
                    </div>
                </div>
            </div>

        </div>
        <div id="step12" class="step" data-valid="false" data-indicator="false">
            <h2 class="thank-you"><?php _e('Thank you, our lenders will contact you shortly') ?></h2>
        </div>
    </div>
</div>

